export BIGDFT_DEFAULT_MPI_FLAVOUR="ompi"
export BIGDFT_SYSTEM="centos"
export BIGDFT_SYSTEM_VERSION="8"
export BIGDFT_CUDA_VERSION="11.4.2"
export BIGDFT_JUPYTER="yes"
export BIGDFT_OPENMPI_VERSION="4.1.1"
export BIGDFT_MVAPICH2_VERSION="2.3.6"
export BIGDFT_VERSION="devel"

export BIGDFT_TOOLCHAIN="gnu"
export BIGDFT_PYTHON="intel"
export BIGDFT_BLAS="mkl"

export BIGDFT_TOOLCHAIN_ARM="arm"
export BIGDFT_PYTHON_ARM="default"
export BIGDFT_BLAS_ARM="arm"

export BIGDFT_TOOLCHAIN_POWER="gnu"
export BIGDFT_PYTHON_POWER="default"
export BIGDFT_BLAS_POWER="openblas"
