# File role: Thin sdk-ground layer from latest SDK image.
# Build options: No args.
# Main stages/targets: base

FROM bigdft/sdk:latest AS base
LABEL maintainer=bigdft-developers@lists.launchpad.net

ENV PYTHON=python3

