#
# This Dockerfile installs a BigDFT-ready build environment with GPU support
# It does not provide BigDFT. V_sim-dev can be conpiled with BigDFT in this container
#

#build stage : heavy image, will be discarded after build 
FROM nvidia/cuda:8.0-devel-ubuntu16.04
LABEL maintainer bigdft-developers@lists.launchpad.net 

WORKDIR /opt/bigdft

#install needed dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        autoconf autotools-dev automake \
        bzr gfortran libblas-dev liblapack-dev \
        fort77 build-essential curl python-pip python-dev \
        bison libz-dev pkg-config python-setuptools \
        libpcre3-dev libtool libglib2.0-dev libltdl-dev \
        gnome-common ipython ipython-notebook \
        python-matplotlib ocl-icd-libopencl1 vim wget \
        net-tools ethtool perl lsb-release iproute2 \
        pciutils libnl-route-3-200 kmod libnuma1 \
        lsof linux-headers-generic python-libxml2 \
        graphviz tk tcl swig chrpath dpatch flex cmake libxml2-dev\
        ssh gdb strace git libglu1-mesa-dev pkg-config libglib2.0-dev \
	libnetcdf-dev libopenbabel-dev \
	intltool libtool gtk-doc-tools libgtk-3-dev \
	python-gobject-dev libyaml-dev \
	libgirepository1.0-dev 

RUN apt-get install -y --no-install-recommends \
        libibverbs-dev libibverbs1 libibcm1 \
        librdmacm1 librdmacm-dev rdmacm-utils \
        byacc libmlx5-1 libgomp1 libibmad5 \
        libibumad3 infiniband-diags \
        opensm libmlx5-dev perftest ibverbs-utils \
        alien
#build with mvapich
WORKDIR /tmp
RUN curl -O http://mvapich.cse.ohio-state.edu/download/mvapich/gdr/2.2/stock2/mvapich2-gdr-2.2-4.cuda8.0.stock.gnu4.8.5.el7.centos.x86_64.rpm && alien -c *.rpm && mkdir /usr/local/mvapich && dpkg --install *.deb && rm -f *.rpm *.deb
RUN cp -r /opt/mvapich2/gdr/no-mcast/2.2/cuda8.0/mpirun/gnu4.8.5/* /usr/local/mvapich

#mvapich needs bash
RUN ln -s /bin/bash /usr/bin/bash
SHELL ["/bin/bash", "-c"]
ENV SHELL /bin/bash

#install jupyter
#upgrade pip to avoid annoying message
RUN pip install --upgrade pip && \ 
    pip install scipy jupyter

EXPOSE 8888

#install OpenCL icd file
RUN mkdir -p /etc/OpenCL/vendors && \
    echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

RUN cp /usr/local/cuda/lib64/stubs/libcuda.so /usr/local/lib/libcuda.so.1
RUN cp /usr/local/cuda/lib64/stubs/libnvidia-ml.so /usr/local/lib/libnvidia-ml.so.1

#update ldconfig as /usr/local/lib may not be in the path
RUN echo "/usr/local/mvapich/lib" > /etc/ld.so.conf.d/mpi.conf
#RUN echo "/bigdft/lib" > /etc/ld.so.conf.d/bigdft.conf
RUN ldconfig
ENV PATH "/usr/local/mvapich/bin:${PATH}"

CMD jupyter-notebook --ip=0.0.0.0 --allow-root --NotebookApp.token=bigdft --no-browser

#jhbuild is allergic to root
RUN useradd -ms /bin/bash bigdft
USER bigdft
ENV XDG_CACHE_HOME /home/bigdft/.cache/
WORKDIR /home/bigdft 
RUN MPLBACKEND=Agg python -c "import matplotlib.pyplot"
