FROM ubuntu
LABEL maintainer bigdft-developers@lists.launchpad.net
#install needed dependencies
RUN apt-get update && \
   DEBIAN_FRONTEND=noninteractive apt-get install -y \
   build-essential libblas-dev liblapack-dev cmake openmpi-bin python3 python3-pip curl git libpython3
apt install libopenmpi3
apt install python-is-python3
apt install libblas-dev liblapack-dev
apt install cmake
apt install openmpi-bin
apt install git
apt install python3-distutils
apt install python3-setuptools
apt install wget curl
apt install libpython3.8-dev
apt install nano
apt install emacs
