FROM bigdft/sdk:oneapi-hpc-ground AS base
LABEL maintainer=bigdft-developers@lists.launchpad.net

#install needed dependencies
RUN apt update || true && \
    DEBIAN_FRONTEND="noninteractive" TZ="Europe/Paris" apt-get install -y \
    git git-lfs autoconf libtool libpcre3-dev doxygen zlib1g-dev libbz2-dev libfreetype6-dev bison flex

RUN git config --global user.email "bigdft-project@gmail.com"
RUN git config --global user.name "BigDFT developer"
RUN git lfs install

WORKDIR /opt/bigdft

ENV BIGDFT_SUITE_SOURCES=/opt/bigdft/sources

ENV JHBUILD_RUN_AS_ROOT="please do it"

ENV BIGDFT_SUITE_TARBALLDIR=/opt/bigdft/bigdft-upstream-tarballs

ENV JHBUILD_COMMAND="$PYTHON $BIGDFT_SUITE_SOURCES/bundler/jhbuild.py"

ENV INSTALLATION_COMMAND="$JHBUILD_COMMAND -m $BIGDFT_SUITE_SOURCES/modulesets/upstream.modules -f $BIGDFT_SUITE_SOURCES/rcfiles/oneapi-hpc-upstream.rc"

ENV BIGDFT_SUITE_CHECKOUTROOT=/opt/bigdft/checkoutdir

ENV LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH

RUN mkdir -p $BIGDFT_SUITE_CHECKOUTROOT

RUN echo "\n\
cd /opt/bigdft; $PYTHON $BIGDFT_SUITE_SOURCES/Installer.py build -f oneapi-hpc.rc -y; cd -\n\
" > /bin/compile_bigdft-suite.sh

RUN chmod +x /bin/compile_bigdft-suite.sh

ENV CONTAINER_DATE=25-04-16-1

#RUN git clone --depth 1 -b total https://gitlab.com/l_sim/bigdft-upstream-tarballs.git $BIGDFT_SUITE_TARBALLDIR

RUN git clone --depth 1 -b devel https://gitlab.com/luigigenovese/bigdft-suite.git $BIGDFT_SUITE_SOURCES

FROM base AS precompile-base

RUN $INSTALLATION_COMMAND build PyYAML dbfft onemath
RUN $INSTALLATION_COMMAND clean PyYAML dbfft onemath

FROM precompile-base AS upstream-core-base

RUN $INSTALLATION_COMMAND --conditions=+sycl build core-upstream-suite
RUN $INSTALLATION_COMMAND --conditions=+sycl clean core-upstream-suite

FROM upstream-core-base AS upstream-core

RUN apt update || true && apt-get install -y gettext libmount-dev intltool python3-gi libpcre3-dev

RUN $INSTALLATION_COMMAND --conditions=-python,-devdoc,+simulation,+sirius build boost fftw swig core-upstream-suite
RUN $INSTALLATION_COMMAND --conditions=-python,-devdoc,+simulation,+sirius clean boost fftw swig core-upstream-suite

FROM precompile-base AS upstream-client-base

RUN $INSTALLATION_COMMAND --conditions=+ase,+vdw,+dill,+spg build  client-upstream-suite client-bio-baseplugins
RUN $INSTALLATION_COMMAND --conditions=+ase,+vdw,+dill,+spg clean  client-upstream-suite client-bio-baseplugins

FROM upstream-client-base AS upstream-client

#install needed dependencies
RUN apt update || true && apt-get install -y python3-tk

RUN pip install matplotlib

RUN $INSTALLATION_COMMAND --conditions=+bio,+devdoc,+boost,-amber build  --skip=rdkit boost client-upstream-suite
RUN $INSTALLATION_COMMAND --conditions=+bio,+devdoc,+boost,-amber clean  --skip=simtk boost client-upstream-suite

FROM upstream-client-base AS upstream-suite-base

RUN $INSTALLATION_COMMAND --conditions=+sycl build upstream-suite
RUN $INSTALLATION_COMMAND --conditions=+sycl clean upstream-suite

FROM upstream-client AS upstream-suite

RUN apt update || true &&  apt-get install -y gettext libmount-dev intltool python3-gi

RUN $INSTALLATION_COMMAND --conditions=-python,-devdoc,+simulation,+sirius,+boost build upstream-suite
RUN $INSTALLATION_COMMAND --conditions=-python,-devdoc,+simulation,+sirius,+boost clean upstream-suite

FROM upstream-core-base AS runtime-core-base

RUN echo rerun
RUN compile_bigdft-suite.sh

FROM upstream-core AS runtime-core

RUN compile_bigdft-suite.sh

FROM upstream-suite AS sdk

#install needed dependencies
RUN apt update || true && \
    apt-get install -y \
    gdb valgrind vim graphviz sshpass  
#intel-opencl-icd intel-oneapi-dpcpp-ct

RUN apt-get install rsync --no-install-recommends -y

RUN ln -s /usr/lib/x86_64-linux-gnu/libpthread.so.0 /usr/lib/x86_64-linux-gnu/libpthread.so

EXPOSE 8888

ENV SDK_CONTAINER_DATE=25-05-22-1

RUN pip install jupyterlab py3dmol xlrd openpyxl mplcursors clustergrammer_widget remotemanager networkx seaborn pillow python-constraint tinydb parmed lxml pint typing-extensions importlib_resources cachetools cairosvg pubchempy propka bokeh xlsxwriter

#RUN for f in /opt/intel/oneapi/intelpython/python3.9/lib/*tinfo.*; do mv $f $f.bak;done

RUN echo "\n\ 
   source /opt/bigdft/install/bin/bigdftvars.sh\n\
   ulimit -s unlimited\n\
   jupyter-lab --ip=0.0.0.0 --allow-root --NotebookApp.token=bigdft --no-browser\n\
" > /bin/run_notebook.sh

CMD ["bash", "/bin/run_notebook.sh"]

FROM runtime-core AS runtime

RUN compile_bigdft-suite.sh

