FROM intel/oneapi-hpckit AS sdkbase
LABEL maintainer bigdft-developers@lists.launchpad.net

#install needed dependencies
RUN apt-get update && \
    apt-get install -y \
    autoconf curl libpcre3-dev git doxygen gdb valgrind vim graphviz zlib1g-dev libbz2-dev gettext libmount-dev bison flex intltool libtool gtk-doc-tools libglu1-mesa-dev libgtk-3-dev

RUN apt-get install rsync --no-install-recommends -y

RUN git config --global user.email "bigdft-project@gmail.com"
RUN git config --global user.name "BigDFT developer"

EXPOSE 8888

WORKDIR /opt/bigdft

RUN /opt/intel/oneapi/intelpython/latest/bin/pip install jupyterlab py3dmol networkx xlrd openpyxl mplcursors seaborn clustergrammer_widget pillow python-constraint tinydb parmed lxml

FROM sdkbase AS sdkseed

RUN git clone --depth 1 -b 1.9.3 https://gitlab.com/luigigenovese/bigdft-suite sources

FROM sdkseed AS sdk_pre

WORKDIR /opt/upstream

ENV JHBUILD_RUN_AS_ROOT "please do it"

RUN export PYTHON_INCLUDE=`python3-config --includes | awk '{print $1}' | sed s/-I//g` && echo "\n    using python \n     : 3.7       \n     : /opt/intel/oneapi/intelpython/latest/bin/python \n     : $PYTHON_INCLUDE  \n     : /opt/intel/oneapi/intelpython/latest/lib  \n     ; \n " > /opt/bigdft/sources/boost-user-config.jam

FROM sdk_pre AS sdk_full

RUN python3 /opt/bigdft/sources/bundler/jhbuild.py -f /opt/bigdft/bigdft-suite/rcfiles/oneapi-hpc.rc build upstream-suite

FROM sdkseed AS sdkcore_pre

COPY --from=sdk_full /opt/upstream /opt/upstream

RUN cd sources && git pull && cd ../

ENV JHBUILD_RUN_AS_ROOT "please do it"

FROM sdkcore_pre AS sdkcore

RUN python3 /opt/bigdft/sources/bundler/jhbuild.py -f /opt/bigdft/sources/rcfiles/oneapi-hpc-core.rc build core-upstream-suite

FROM sdkbase AS sdkfull

COPY --from=sdkclient /opt/client-upstream /opt/client-upstream
COPY --from=sdkcore /opt/core-upstream /opt/core-upstream

RUN echo "\n\ 
   source /opt/bigdft/install/bin/bigdftvars.sh\n\
   ulimit -s unlimited\n\
   jupyter-lab --ip=0.0.0.0 --allow-root --NotebookApp.token=bigdft --no-browser\n\
" > /bin/run_notebook.sh

RUN echo "\n\
cd /opt/bigdft; python3 /opt/bigdft/sources/Installer.py build -f oneapi-hpc-full.rc -y; cd -\n\
" > /bin/compile_bigdft-suite.sh

RUN chmod +x /bin/compile_bigdft-suite.sh

CMD bash /bin/run_notebook.sh

FROM sdkfull AS runtime

COPY --from=sdkclient /opt/bigdft/sources /opt/bigdft/sources

WORKDIR /opt/bigdft/

RUN cd sources && git pull && cd ../

ENV JHBUILD_RUN_AS_ROOT "please do it"

RUN compile_bigdft-suite.sh 
