FROM bigdft/sdk:oneapi-ground AS base

#install needed dependencies
RUN apt update || true && \
    apt-get install -y \
    autoconf curl libpcre3-dev git doxygen zlib1g-dev libbz2-dev gettext libmount-dev bison flex intltool libtool git-lfs gawk libfreetype6-dev rubygems libffi-dev ruby-dev vim less gdb

RUN git config --global user.email "bigdft-project@gmail.com"
RUN git config --global user.name "BigDFT developer"
RUN git lfs install

RUN git clone https://github.com/Nanosim-LIG/boast && cd boast/ && gem build BOAST.gemspec && gem install BOAST-2.1.0.gem && cd ../

RUN ln -s /usr/lib/x86_64-linux-gnu/libpthread.so.0 /usr/lib/x86_64-linux-gnu/libpthread.so

