# Copyright (c) 2020-2021 Intel Corporation.
# SPDX-License-Identifier: BSD-3-Clause

FROM ubuntu:24.04
RUN apt-get update && apt-get upgrade -y && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    curl ca-certificates gpg-agent software-properties-common && \
  rm -rf /var/lib/apt/lists/*
# repository to install Intel(R) oneAPI Libraries
RUN curl -fsSL https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB | gpg --dearmor | tee /usr/share/keyrings/intel-oneapi-archive-keyring.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/intel-oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main " > /etc/apt/sources.list.d/oneAPI.list

RUN apt-get update && apt-get upgrade -y && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    curl ca-certificates gpg-agent software-properties-common && \
  rm -rf /var/lib/apt/lists/*
# repository to install Intel(R) GPU drivers
RUN curl -fsSL https://repositories.intel.com/gpu/intel-graphics.key | gpg --dearmor | tee /usr/share/keyrings/intel-graphics-archive-keyring.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/intel-graphics-archive-keyring.gpg arch=amd64] https://repositories.intel.com/gpu/ubuntu noble unified" > /etc/apt/sources.list.d/intel-graphics.list

RUN apt-get update && apt-get upgrade -y && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates build-essential pkg-config gnupg libarchive13 openssh-server openssh-client wget net-tools git cmake intel-cpp-essentials  intel-fortran-essentials intel-opencl-icd libze-intel-gpu1 libze1 libze-dev clinfo git-lfs autoconf libtool libpcre3-dev doxygen zlib1g-dev libbz2-dev libfreetype6-dev bison flex python3-setuptools python3-dev automake && \
  rm -rf /var/lib/apt/lists/*

ENV LANG=C.UTF-8
ENV ADVISOR_2025_DIR='/opt/intel/oneapi/advisor/2025.1'
ENV CMAKE_PREFIX_PATH='/opt/intel/oneapi/tbb/2022.1/env/..:/opt/intel/oneapi/pti/0.11/lib/cmake/pti:/opt/intel/oneapi/mkl/2025.1/lib/cmake:/opt/intel/oneapi/ipp/2022.1/lib/cmake/ipp:/opt/intel/oneapi/dpl/2022.8/lib/cmake/oneDPL:/opt/intel/oneapi/dnnl/2025.1/lib/cmake:/opt/intel/oneapi/dal/2025.4:/opt/intel/oneapi/compiler/2025.1:/opt/intel/oneapi/ccl/2021.15/lib/cmake/oneCCL'
ENV CMPLR_ROOT='/opt/intel/oneapi/compiler/2025.1'
ENV CPATH='/opt/intel/oneapi/umf/0.10/include:/opt/intel/oneapi/tbb/2022.1/env/../include:/opt/intel/oneapi/pti/0.11/include:/opt/intel/oneapi/mpi/2021.15/include:/opt/intel/oneapi/mkl/2025.1/include:/opt/intel/oneapi/ishmem/1.3/include:/opt/intel/oneapi/ippcp/2025.1/include:/opt/intel/oneapi/ipp/2022.1/include:/opt/intel/oneapi/dpl/2022.8/include:/opt/intel/oneapi/dpcpp-ct/2025.1/include:/opt/intel/oneapi/dnnl/2025.1/include:/opt/intel/oneapi/dev-utilities/2025.1/include:/opt/intel/oneapi/dal/2025.4/include:/opt/intel/oneapi/dal/2025.4/include/dal:/opt/intel/oneapi/ccl/2021.15/include'
ENV GDB_INFO='/opt/intel/oneapi/debugger/2025.1/share/info/'
ENV INFOPATH='/opt/intel/oneapi/debugger/2025.1/share/info'
ENV INTEL_PYTHONHOME='/opt/intel/oneapi/debugger/2025.1/opt/debugger'
ENV IPPCP_TARGET_ARCH='intel64'
ENV IPPCRYPTOROOT='/opt/intel/oneapi/ippcp/2025.1'
ENV IPPROOT='/opt/intel/oneapi/ipp/2022.1'
ENV IPP_TARGET_ARCH='intel64'
ENV ISHMEM_ROOT='/opt/intel/oneapi/ishmem/1.3'
ENV I_MPI_ROOT='/opt/intel/oneapi/mpi/2021.15'
ENV LD_LIBRARY_PATH='/opt/intel/oneapi/tcm/1.3/lib:/opt/intel/oneapi/umf/0.10/lib:/opt/intel/oneapi/tbb/2022.1/env/../lib/intel64/gcc4.8:/opt/intel/oneapi/pti/0.11/lib:/opt/intel/oneapi/mpi/2021.15/opt/mpi/libfabric/lib:/opt/intel/oneapi/mpi/2021.15/lib:/opt/intel/oneapi/mkl/2025.1/lib:/opt/intel/oneapi/ishmem/1.3/lib:/opt/intel/oneapi/ippcp/2025.1/lib/:/opt/intel/oneapi/ipp/2022.1/lib:/opt/intel/oneapi/dnnl/2025.1/lib:/opt/intel/oneapi/debugger/2025.1/opt/debugger/lib:/opt/intel/oneapi/dal/2025.4/lib:/opt/intel/oneapi/compiler/2025.1/opt/compiler/lib:/opt/intel/oneapi/compiler/2025.1/lib:/opt/intel/oneapi/ccl/2021.15/lib/'
ENV LIBRARY_PATH='/opt/intel/oneapi/tcm/1.3/lib:/opt/intel/oneapi/umf/0.10/lib:/opt/intel/oneapi/tbb/2022.1/env/../lib/intel64/gcc4.8:/opt/intel/oneapi/pti/0.11/lib:/opt/intel/oneapi/mpi/2021.15/lib:/opt/intel/oneapi/mkl/2025.1/lib:/opt/intel/oneapi/ishmem/1.3/lib:/opt/intel/oneapi/ippcp/2025.1/lib/:/opt/intel/oneapi/ipp/2022.1/lib:/opt/intel/oneapi/dnnl/2025.1/lib:/opt/intel/oneapi/dal/2025.4/lib:/opt/intel/oneapi/compiler/2025.1/lib:/opt/intel/oneapi/ccl/2021.15/lib/'
ENV MANPATH='/opt/intel/oneapi/mpi/2021.15/share/man:/opt/intel/oneapi/debugger/2025.1/share/man:/opt/intel/oneapi/compiler/2025.1/share/man:'
ENV MKLROOT='/opt/intel/oneapi/mkl/2025.1'
ENV NLSPATH='/opt/intel/oneapi/compiler/2025.1/lib/compiler/locale/%l_%t/%N'
ENV OCL_ICD_FILENAMES='/opt/intel/oneapi/compiler/2025.1/lib/libintelocl.so'
ENV ONEAPI_ROOT='/opt/intel/oneapi'
ENV PATH='/opt/intel/oneapi/vtune/2025.1/bin64:/opt/intel/oneapi/mpi/2021.15/bin:/opt/intel/oneapi/mkl/2025.1/bin:/opt/intel/oneapi/ishmem/1.3/bin:/opt/intel/oneapi/dpcpp-ct/2025.1/bin:/opt/intel/oneapi/dev-utilities/2025.1/bin:/opt/intel/oneapi/debugger/2025.1/opt/debugger/bin:/opt/intel/oneapi/compiler/2025.1/bin:/opt/intel/oneapi/advisor/2025.1/bin64:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
ENV PKG_CONFIG_PATH='/opt/intel/oneapi/vtune/2025.1/include/pkgconfig/lib64:/opt/intel/oneapi/tbb/2022.1/env/../lib/pkgconfig:/opt/intel/oneapi/mpi/2021.15/lib/pkgconfig:/opt/intel/oneapi/mkl/2025.1/lib/pkgconfig:/opt/intel/oneapi/ippcp/2025.1/lib/pkgconfig:/opt/intel/oneapi/dpl/2022.8/lib/pkgconfig:/opt/intel/oneapi/dnnl/2025.1/lib/pkgconfig:/opt/intel/oneapi/dal/2025.4/lib/pkgconfig:/opt/intel/oneapi/compiler/2025.1/lib/pkgconfig:/opt/intel/oneapi/ccl/2021.15/lib/pkgconfig/:/opt/intel/oneapi/advisor/2025.1/include/pkgconfig/lib64:'
ENV PYTHONPATH='/opt/intel/oneapi/advisor/2025.1/pythonapi'

#ENV INTELPYTHON=/opt/intel/oneapi/intelpython3 
ENV PYTHON=python3
#ENV PATH="$INTELPYTHON/bin:$PATH"
ENV I_MPI_FABRICS=shm

# Add persistent exit confirmation logic
RUN printf '%s\n' \
 '# Confirm before real shell exit (on Ctrl+D or termination)' \
  'trap_exit() {' \
  '  # Remove trap temporarily to prevent infinite loop' \
  '  trap - EXIT' \
  '  read -p "Are you sure you want to exit (UNDER_JHBUILD=$UNDER_JHBUILD) ? (y/N): " answer' \
  '  case "$answer" in' \
  '    [Yy]*) echo "Exiting..."; builtin exit ;;' \
  '    *) echo "Exit canceled."; exec "$SHELL" ;;' \
  '  esac' \
  '}' \
  '' \
  'trap trap_exit EXIT' \
  >> /etc/bash.bashrc

RUN git config --global user.email "bigdft-project@gmail.com"
RUN git config --global user.name "BigDFT developer"
RUN git lfs install

WORKDIR /opt/bigdft

ENV BIGDFT_SUITE_SOURCES=/opt/bigdft/sources

ENV JHBUILD_RUN_AS_ROOT="please do it"

ENV BIGDFT_SUITE_TARBALLDIR=/opt/bigdft/bigdft-upstream-tarballs

ENV JHBUILD_COMMAND="$PYTHON $BIGDFT_SUITE_SOURCES/bundler/jhbuild.py"

ENV INSTALLATION_COMMAND="$JHBUILD_COMMAND -m $BIGDFT_SUITE_SOURCES/modulesets/upstream.modules -f $BIGDFT_SUITE_SOURCES/rcfiles/oneapi-hpc-upstream.rc"

ENV BIGDFT_SUITE_CHECKOUTROOT=/opt/bigdft/checkoutdir

ENV LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH

ENV PYTHONPATH='/opt/upstream/local/python3.12/dist-packages':$PYTHONPATH

RUN mkdir -p $BIGDFT_SUITE_CHECKOUTROOT

RUN echo "\n\
cd /opt/bigdft; $PYTHON $BIGDFT_SUITE_SOURCES/Installer.py build -f oneapi-hpc.rc -y; cd -\n\
" > /bin/compile_bigdft-suite.sh

RUN chmod +x /bin/compile_bigdft-suite.sh

ENV CONTAINER_DATE=25-04-29-1

#RUN git clone --depth 1 -b total https://gitlab.com/l_sim/bigdft-upstream-tarballs.git $BIGDFT_SUITE_TARBALLDIR

RUN git clone --depth 1 -b devel https://gitlab.com/luigigenovese/bigdft-suite.git $BIGDFT_SUITE_SOURCES

RUN $INSTALLATION_COMMAND --conditions=+sycl build onemath core-upstream-suite
RUN $INSTALLATION_COMMAND --conditions=+sycl clean onemath core-upstream-suite

ENV INTELPYTHON=$PYTHON
ENV PYTHONPATH=/opt/upstream/local/lib/python3.12/dist-packages
