# Copyright (c) 2020-2021 Intel Corporation.
# SPDX-License-Identifier: BSD-3-Clause
FROM bigdft/ground:oneapi25.1-intel AS base
LABEL maintainer=bigdft-developers@lists.launchpad.net

RUN git config --global user.email "bigdft-project@gmail.com"
RUN git config --global user.name "BigDFT developer"
RUN git lfs install

WORKDIR /opt/bigdft

ENV BIGDFT_SUITE_SOURCES=/opt/bigdft/sources

ENV JHBUILD_RUN_AS_ROOT="please do it"

ENV BIGDFT_SUITE_TARBALLDIR=/opt/bigdft/bigdft-upstream-tarballs

ENV JHBUILD_COMMAND="$PYTHON $BIGDFT_SUITE_SOURCES/bundler/jhbuild.py"

ENV INSTALLATION_COMMAND="$JHBUILD_COMMAND -m $BIGDFT_SUITE_SOURCES/modulesets/upstream.modules -f $BIGDFT_SUITE_SOURCES/rcfiles/oneapi-hpc-upstream.rc"

ENV BIGDFT_SUITE_CHECKOUTROOT=/opt/bigdft/checkoutdir

ENV LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH

ENV PYTHONPATH='/opt/upstream/local/python3.12/dist-packages':$PYTHONPATH

RUN mkdir -p $BIGDFT_SUITE_CHECKOUTROOT

RUN echo "\n\
cd /opt/bigdft; $PYTHON $BIGDFT_SUITE_SOURCES/Installer.py build -f oneapi-hpc.rc -y; cd -\n\
" > /bin/compile_bigdft-suite.sh

RUN chmod +x /bin/compile_bigdft-suite.sh

ENV CONTAINER_DATE=25-06-23-3

RUN git clone --depth 1 -b total https://gitlab.com/l_sim/bigdft-upstream-tarballs.git $BIGDFT_SUITE_TARBALLDIR

RUN git clone --depth 1  -b devel https://gitlab.com/l_sim/bigdft-suite.git $BIGDFT_SUITE_SOURCES

FROM base AS upstream-core-base

RUN $INSTALLATION_COMMAND --conditions=+sycl build onemath core-upstream-suite
RUN $INSTALLATION_COMMAND --conditions=+sycl clean onemath core-upstream-suite

ENV INTELPYTHON=$PYTHON
ENV PYTHONPATH=/opt/upstream/local/lib/python3.12/dist-packages

FROM upstream-core-base AS upstream-core

RUN apt-get update && apt-get upgrade -y && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    gettext libmount-dev intltool python3-gi libpcre3-dev && \
  rm -rf /var/lib/apt/lists/*

RUN $INSTALLATION_COMMAND --conditions=-python,-devdoc,+simulation,+sirius build boost fftw swig core-upstream-suite
RUN $INSTALLATION_COMMAND --conditions=-python,-devdoc,+simulation,+sirius clean boost fftw swig core-upstream-suite

FROM base AS upstream-client-base

RUN $INSTALLATION_COMMAND --conditions=+ase,+vdw,+dill,+spg build  client-upstream-suite client-bio-baseplugins
RUN $INSTALLATION_COMMAND --conditions=+ase,+vdw,+dill,+spg clean  client-upstream-suite client-bio-baseplugins

FROM upstream-client-base AS upstream-client

#install needed dependencies
RUN apt-get update && apt-get upgrade -y && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    gettext libmount-dev intltool python3-gi libpcre3-dev python3-tk && \
  rm -rf /var/lib/apt/lists/*

RUN pip3 install matplotlib

RUN $INSTALLATION_COMMAND --conditions=+bio,+devdoc,+boost,-amber build  --skip=rdkit boost client-upstream-suite
RUN $INSTALLATION_COMMAND --conditions=+bio,+devdoc,+boost,-amber clean  --skip=simtk boost client-upstream-suite

FROM base AS upstream-suite

#install needed dependencies
RUN apt-get update && apt-get upgrade -y && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    gettext libmount-dev intltool python3-gi libpcre3-dev python3-tk && \
  rm -rf /var/lib/apt/lists/*

RUN pip install matplotlib Cython scipy --break-system-packages

ENV CONDITIONS=+sycl,-python,+devdoc,+simulation,+sirius,+ase,+vdw,+dill,+spg,+bio,+boost,+amber
ENV PACKAGES="onemath boost fftw swig upstream-suite"

RUN $INSTALLATION_COMMAND --conditions=$CONDITIONS build --skip=rdkit $PACKAGES && $INSTALLATION_COMMAND --conditions=$CONDITIONS clean --skip=simtk $PACKAGES

FROM upstream-core-base AS runtime-core-base

RUN compile_bigdft-suite.sh

FROM upstream-core AS runtime-core

RUN compile_bigdft-suite.sh

FROM upstream-suite AS sdk

#install needed dependencies
RUN apt-get update && apt-get upgrade -y && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    gdb valgrind vim graphviz sshpass rsync && \
  rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/lib/x86_64-linux-gnu/libpthread.so.0 /usr/lib/x86_64-linux-gnu/libpthread.so

EXPOSE 8888

ENV SDK_CONTAINER_DATE=25-06-22-1

RUN pip install jupyterlab py3dmol xlrd openpyxl mplcursors clustergrammer_widget remotemanager networkx seaborn pillow python-constraint tinydb parmed lxml pint typing-extensions importlib_resources cachetools cairosvg pubchempy propka bokeh xlsxwriter --break-system-packages

#RUN for f in /opt/intel/oneapi/intelpython/python3.9/lib/*tinfo.*; do mv $f $f.bak;done

RUN echo "\n\ 
   source /opt/bigdft/install/bin/bigdftvars.sh\n\
   ulimit -s unlimited\n\
   jupyter-lab --ip=0.0.0.0 --allow-root --NotebookApp.token=bigdft --no-browser\n\
" > /bin/run_notebook.sh

CMD ["bash", "/bin/run_notebook.sh"]


