FROM ubuntu
LABEL maintainer bigdft-developers@lists.launchpad.net
#install needed dependencies
RUN apt-get update && \
   DEBIAN_FRONTEND=noninteractive apt-get install -y \
   build-essential libblas-dev liblapack-dev cmake openmpi-bin python3 python3-pip curl git

