FROM intel/oneapi-hpckit AS sdkbase
LABEL maintainer bigdft-developers@lists.launchpad.net

#install needed dependencies
RUN apt-get update && \
    apt-get install -y \
    autoconf curl libpcre3-dev git doxygen gdb valgrind vim graphviz zlib1g-dev libbz2-dev gettext libmount-dev bison flex intltool libtool gtk-doc-tools libglu1-mesa-dev libgtk-3-dev

RUN apt-get install rsync --no-install-recommends -y

RUN git config --global user.email "bigdft-project@gmail.com"
RUN git config --global user.name "BigDFT developer"

EXPOSE 8888

WORKDIR /opt/bigdft

RUN /opt/intel/oneapi/intelpython/latest/bin/pip install jupyterlab py3dmol networkx xlrd openpyxl mplcursors seaborn clustergrammer_widget pillow python-constraint tinydb parmed lxml

RUN echo "\n\
cd /opt/bigdft; python3 /opt/bigdft/sources/Installer.py build -f oneapi-hpc-full.rc -y; cd -\n\
" > /bin/compile_bigdft-suite.sh

RUN chmod +x /bin/compile_bigdft-suite.sh

WORKDIR /opt/bigdft

ENV JHBUILD_RUN_AS_ROOT "please do it"

FROM sdkbase AS sdkseed

RUN git clone --depth 1 -b 1.9.3-new https://gitlab.com/luigigenovese/bigdft-suite sources

FROM sdkseed AS sdk_pre

RUN export PYTHON_INCLUDE=`python3-config --includes | awk '{print $1}' | sed s/-I//g` && echo "\n    using python \n     : 3.7       \n     : /opt/intel/oneapi/intelpython/latest/bin/python \n     : $PYTHON_INCLUDE  \n     : /opt/intel/oneapi/intelpython/latest/lib  \n     ; \n " > /opt/bigdft/sources/boost-user-config.jam

ENV BIGDFT_SUITE_SOURCES /opt/bigdft/sources

FROM sdk_pre AS sdk_bio

RUN python3 $BIGDFT_SUITE_SOURCES/bundler/jhbuild.py -f $BIGDFT_SUITE_SOURCES/rcfiles/oneapi-hpc.rc -m $BIGDFT_SUITE_SOURCES/modulesets/upstream.modules build client-bio-plugins

FROM sdk_bio AS sdk_client

RUN python3 $BIGDFT_SUITE_SOURCES/bundler/jhbuild.py -f $BIGDFT_SUITE_SOURCES/rcfiles/oneapi-hpc.rc -m $BIGDFT_SUITE_SOURCES/modulesets/upstream.modules build client-plugins

FROM sdk_client AS sdk_full

RUN python3 $BIGDFT_SUITE_SOURCES/bundler/jhbuild.py -f $BIGDFT_SUITE_SOURCES/rcfiles/oneapi-hpc.rc -m $BIGDFT_SUITE_SOURCES/modulesets/upstream.modules build upstream-suite

RUN compile_bigdft-suite.sh

FROM sdkseed AS sdk

COPY --from=sdk_full /opt/upstream /opt/upstream

RUN echo "\n\ 
   source /opt/bigdft/install/bin/bigdftvars.sh\n\
   ulimit -s unlimited\n\
   jupyter-lab --ip=0.0.0.0 --allow-root --NotebookApp.token=bigdft --no-browser\n\
" > /bin/run_notebook.sh

CMD bash /bin/run_notebook.sh

FROM sdk_full AS runtime

COPY --from=sdk_full /opt/bigdft/install /opt/bigdft/install/

