name: aiidalab
on: [workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
        -   uses: actions/checkout@v2
        -   name: Login to DockerHub Registry
            run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        -   name: Build the Docker image
            working-directory: aiidalab-sshonly
            run: |
                d=$(date +%Y-%m-%d--%H-%M-%S)
                docker build . --file Dockerfile --tag bigdft/aiidalab-docker:latest --tag bigdft/aiidalab-docker:$d
        -   name: Push the tagged Docker image
            run: |
                docker image push --all-tags bigdft/aiidalab-docker
