name: continuous-integration
on: [push, workflow_dispatch]
jobs:
    generate:
        strategy:
            matrix:
                mpi: [ompi]
        runs-on: ubuntu-20.04
        steps:
        -   uses: actions/checkout@v2
        -   name: Cache python dependencies
            id: cache-pip
            uses: actions/cache@v1
            with:
                path: ~/.cache/pip
                key: pip-pre-commit-${{ hashFiles('**/setup.json') }}
                restore-keys:
                    pip-pre-commit-
        -   name: Set up Python
            uses: actions/setup-python@v1
            with:
                python-version: 3.8
        -   name: Install python dependencies
            run:
                pip install hpccm
        -   name: Get the tag and MPI version
            id: vars
            run: |
                source current_setup.sh 
                if [ ${{ matrix.mpi }} == "mvapich" ]; then
                    echo ::set-output name=version::$(echo $BIGDFT_MVAPICH2_VERSION) 
                else
                    echo ::set-output name=version::$(echo $BIGDFT_OPENMPI_VERSION) 
                fi          
                echo ::set-output name=tag::$(echo ubuntu${BIGDFT_UBUNTU_VERSION}_cuda${BIGDFT_CUDA_VERSION}_${{ matrix.mpi }}${{steps.vars.outputs.version}}_${GITHUB_REF##*/})
        -   name: generate docker files for openmpi
            run: |
                source current_setup.sh
                hpccm --recipe hpccm/hpccm_lsim-mpi.py --userarg cuda=${BIGDFT_CUDA_VERSION} ubuntu=${BIGDFT_UBUNTU_VERSION} mpi=${{ matrix.mpi }} mpi_version=${{steps.vars.outputs.version}} > Dockerfile_sdk_${{ matrix.mpi }}
                hpccm --recipe hpccm/hpccm_lsim-vsim.py --userarg cuda=${BIGDFT_CUDA_VERSION} ubuntu=${BIGDFT_UBUNTU_VERSION} mpi=${{ matrix.mpi }} mpi_version=${{steps.vars.outputs.version}} tag="bigdft/sdk:${{steps.vars.outputs.tag}}" > Dockerfile_vsim_${{ matrix.mpi }}
                hpccm --recipe hpccm/hpccm_lsim-bigdft.py --userarg cuda=${BIGDFT_CUDA_VERSION} ubuntu=${BIGDFT_UBUNTU_VERSION} mpi=${{ matrix.mpi }} mpi_version=${{steps.vars.outputs.version}} tag="bigdft/sdk:${{steps.vars.outputs.tag}}" > Dockerfile_runtime_${{ matrix.mpi }}
        -   name: Upload sdk dockerfile
            uses: actions/upload-artifact@v1
            with:
                name: dockerfile_sdk_${{ matrix.mpi }}
                path: Dockerfile_sdk_${{ matrix.mpi }}
        -   name: Upload vsim dockerfile
            uses: actions/upload-artifact@v1
            with:
                name: dockerfile_vsim_${{ matrix.mpi }}
                path: Dockerfile_vsim_${{ matrix.mpi }}
        -   name: Upload runtime dockerfile
            uses: actions/upload-artifact@v1
            with:
                name: dockerfile_runtime_${{ matrix.mpi }}
                path: Dockerfile_runtime_${{ matrix.mpi }}
    build_sdk:
        strategy:
            matrix:
                mpi: [ompi]
        runs-on: ubuntu-20.04
        needs: generate
        steps:
        -   uses: actions/checkout@v2
        -   name: Download dockerfile
            uses: actions/download-artifact@v1
            with:
                name: dockerfile_sdk_${{ matrix.mpi }}
        -   name: Login to DockerHub Registry
            run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        -   name: Get the tag and MPI version
            id: vars
            run: |
                source current_setup.sh 
                if [ ${{ matrix.mpi }} == "mvapich" ]; then
                    echo ::set-output name=version::$(echo $BIGDFT_MVAPICH2_VERSION) 
                else
                    echo ::set-output name=version::$(echo $BIGDFT_OPENMPI_VERSION) 
                fi          
                echo ::set-output name=tag::$(echo ubuntu${BIGDFT_UBUNTU_VERSION}_cuda${BIGDFT_CUDA_VERSION}_${{ matrix.mpi }}${{steps.vars.outputs.version}}_${GITHUB_REF##*/})
        -   name: Build the tagged Docker image
            run: docker build . --file dockerfile_sdk_${{ matrix.mpi }}/Dockerfile_sdk_${{ matrix.mpi }} --tag bigdft/sdk:${{steps.vars.outputs.tag}} --tag bigdft/sdk:latest
        -   name: Push the tagged Docker image
            run: |
                docker push bigdft/sdk:${{steps.vars.outputs.tag}}
                if [ ${{ matrix.mpi }} == "ompi" ]; then
                    docker push bigdft/sdk:latest 
                fi
    build_vsim:
        runs-on: ubuntu-latest
        needs: build_sdk
        strategy:
            matrix:
                mpi: [ompi]
        steps:
        -   uses: actions/checkout@v2
        -   name: Download dockerfile
            uses: actions/download-artifact@v1
            with:
                name: dockerfile_vsim_${{ matrix.mpi }}
        -   name: Login to DockerHub Registry
            run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        -   name: Get the tag and MPI version
            id: vars
            run: |
                source current_setup.sh 
                if [ ${{ matrix.mpi }} == "mvapich" ]; then
                    echo ::set-output name=version::$(echo $BIGDFT_MVAPICH2_VERSION) 
                else
                    echo ::set-output name=version::$(echo $BIGDFT_OPENMPI_VERSION) 
                fi          
                echo ::set-output name=tag::$(echo ubuntu${BIGDFT_UBUNTU_VERSION}_cuda${BIGDFT_CUDA_VERSION}_${{ matrix.mpi }}${{steps.vars.outputs.version}}_${GITHUB_REF##*/})
        -   name: Build the tagged Docker image
            run: docker build . --file dockerfile_vsim_${{ matrix.mpi }}/Dockerfile_vsim_${{ matrix.mpi }} --tag bigdft/vsim:${{steps.vars.outputs.tag}} --tag bigdft/vsim:latest
        -   name: Push the tagged Docker image
            run: |
                docker push bigdft/vsim:${{steps.vars.outputs.tag}}
                if [ ${{ matrix.mpi }} == "ompi" ]; then
                    docker push bigdft/vsim:latest 
                fi
    build_runtime:
        runs-on: ubuntu-latest
        needs: build_sdk
        strategy:
            matrix:
                mpi: [ompi]
        steps:
        -   uses: actions/checkout@v2
        -   name: Download dockerfile
            uses: actions/download-artifact@v1
            with:
                name: dockerfile_runtime_${{ matrix.mpi }}
        -   name: Login to DockerHub Registry
            run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        -   name: Get the tag and MPI version
            id: vars
            run: |
                source current_setup.sh 
                if [ ${{ matrix.mpi }} == "mvapich" ]; then
                    echo ::set-output name=version::$(echo $BIGDFT_MVAPICH2_VERSION) 
                else
                    echo ::set-output name=version::$(echo $BIGDFT_OPENMPI_VERSION) 
                fi          
                echo ::set-output name=tag::$(echo ubuntu${BIGDFT_UBUNTU_VERSION}_cuda${BIGDFT_CUDA_VERSION}_${{ matrix.mpi }}${{steps.vars.outputs.version}}_${GITHUB_REF##*/})
        -   name: Build the tagged Docker image
            run: docker build . --file dockerfile_runtime_${{ matrix.mpi }}/Dockerfile_runtime_${{ matrix.mpi }} --tag bigdft/runtime:${{steps.vars.outputs.tag}} --tag bigdft/runtime:latest
        -   name: Test Fehyb OMP
            working-directory: FeHyb/NOGPU
            run: |
                chmod -R 777 .
                docker run -v $PWD:/results -w /results bigdft/runtime:${{steps.vars.outputs.tag}} bigdft
        -   name: Upload logfile
            uses: actions/upload-artifact@v1
            with:
                name: log-omp-${{ matrix.mpi }}
                path: FeHyb/NOGPU/log.yaml
        -   name: Test Fehyb MPI
            working-directory: FeHyb/NOGPU
            run: |
                docker run -v $PWD:/results -w /results -e OMP_NUM_THREADS=1 bigdft/runtime:${{steps.vars.outputs.tag}} mpirun -np 2 bigdft
        -   name: Upload logfile
            uses: actions/upload-artifact@v1
            with:
                name: log-mpi-${{ matrix.mpi }}
                path: FeHyb/NOGPU/log.yaml        
        -   name: Push the tagged Docker image
            run: |
                docker push bigdft/runtime:${{steps.vars.outputs.tag}}
                if [ ${{ matrix.mpi }} == "ompi" ]; then
                    docker push bigdft/runtime:latest 
                fi
