name: latex
on:
    push:
        paths:
            - Dockerfiles/Dockerfile-latex
            - .github/workflows/latex.yml
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
        -   uses: actions/checkout@v4
        -   name: Login to DockerHub Registry
            run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        -   name: Build the Docker image
            working-directory: Dockerfiles
            run: docker build --file Dockerfile-latex --tag bigdft/latex:latest .  
        -   name: Push the tagged Docker image
            run: |
                d=$(date +%Y-%m-%d--%H-%M-%S)
                docker tag bigdft/latex:latest bigdft/latex:$d
                docker push bigdft/latex:$d
                docker push bigdft/latex:latest
